config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#main'
  get 'top/main', to: 'top#main'
  get 'top/logout', to: 'top#logout'
  get 'top/error', to: 'top#error'
  post 'top/login', to: 'top#login'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.authenticate?(params)
    if User.find_by(uid: params[:uid], pass: params[:pass])
      return true
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:uid].nil?
      render "main"
    else
      render "login"
    end
  end

  def login
    if User.authenticate?(tweet_params)
      session[:uid] ||= params[:uid]
      redirect_to top_main_path
    else
      redirect_to top_error_path
    end
  end

  def logout
    session.delete(:uid)
    redirect_to root_path
  end

  def error

  end

  private

  def tweet_params
    params.permit(:uid, :pass)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swdev04</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>ログイン失敗</h1>
<%= link_to 'もどる', root_path %>

app/views/top/login.html.erb
<h1>ログイン成功</h1>
<%= link_to 'ログアウト', top_logout_path %>

app/views/top/main.html.erb
<h1>Login</h1>
<%= form_with url: 'top/login' do |form| %>
  <%= form.label :uid, 'User ID' %>
  <%= form.text_field :uid %>
  <%= form.label :pass, 'Password' %>
  <%= form.text_field :pass %>
  <%= form.submit 'Submit' %>
<% end %>